# Generated by Django 4.2.1 on 2023-05-31 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagensJogos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('legenda', models.CharField(max_length=300)),
                ('artigo', models.TextField()),
                ('imagem', models.CharField(max_length=500)),
            ],
        ),
    ]
