# Generated by Django 4.2.1 on 2023-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensjogos',
            name='genero',
            field=models.CharField(choices=[('HACKNSLASH', 'Hack & Slash'), ('PLATAFORMA', 'Plataforma'), ('ARCADE', 'Arcade'), ('CORRIDA', 'Corrida'), ('ESTRATEGIA', 'Estratégia'), ('TIRO', 'Tiro'), ('RPG', 'RPG'), ('TABULEIRO', 'Tabuleiro'), ('MUNDO ABERTO', 'Mundo aberto'), ('STEALTH', 'Stealth'), ('LUTA', 'Luta'), ('QUEBRACABECA', 'Quebra-Cabeça'), ('ROGUELIKE', 'RogueLike'), ('SIMULACAO', 'Simulação')], default='', max_length=50),
        ),
    ]
