# Generated by Django 4.2.1 on 2023-06-01 16:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_imagensjogos_publicada'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagensjogos',
            name='data_artigo',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
