# Generated by Django 4.2.1 on 2023-06-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_imagensjogos_data_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagensjogos',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='imagens/%Y/%m/%d/'),
        ),
    ]
